In [4]:
import pandas as pd
import numpy as np

In [42]:
df = pd.DataFrame({
    "Name": [
        "Alice", "Bob", "Charlie", "David", "Eva",
        "Frank", "Grace", "Jack", "Jack", "Jack"
    ],
    "Age": [
        "25", "abc", np.nan, "30", "Unknown",
        "45", "twenty", "18", "", "60"
    ],
    "City": [
        "Delhi", "Mumbai", "Pune", "Ahmedabad", "Surat",
        "Rajkot", "Vadodara", "Jaipur", "Indore", "Bhopal"
    ]
})

In [7]:
df

      Name      Age       City
0    Alice       25      Delhi
1      Bob      abc     Mumbai
2  Charlie      NaN       Pune
3    David       30  Ahmedabad
4      Eva  Unknown      Surat
5    Frank       45     Rajkot
6    Grace   twenty   Vadodara
7    Henry       18     Jaipur
8      Ivy              Indore
9     Jack       60     Bhopal

In [8]:
df.dropna()

    Name      Age       City
0  Alice       25      Delhi
1    Bob      abc     Mumbai
3  David       30  Ahmedabad
4    Eva  Unknown      Surat
5  Frank       45     Rajkot
6  Grace   twenty   Vadodara
7  Henry       18     Jaipur
8    Ivy              Indore
9   Jack       60     Bhopal

In [45]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df.dropna(subset=["Age"], inplace=True)  # returning new dataframe
df["Age"] = df["Age"].astype(int)

In [46]:
df

    Name  Age       City
0  Alice   25      Delhi
3  David   30  Ahmedabad
5  Frank   45     Rajkot
7   Jack   18     Jaipur
9   Jack   60     Bhopal

In [52]:
df.duplicated(subset=["Name"])
df.drop_duplicates(subset=["Name"], inplace=True)

In [53]:
df

    Name  Age       City
0  Alice   25      Delhi
3  David   30  Ahmedabad
5  Frank   45     Rajkot
7   Jack   18     Jaipur